---
title: "Benchmark of supervised integration tools"
author: "Leonard Herault"
date: '2022-12-09'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,comment = FALSE,warning = FALSE)
```

## libraries

```{r cars}
library(ggplot2)
library(Seurat)
library(ggrepel)
```




```{bash}
#cp visualization/scIB_knit_table.R ../scib-pipeline/reports/
#mv scIB_knit_table.R knit_table.R
```

```{r}
# install.packages('dynutils')
# install.packages('magick')
# install.packages('cowplot')
# install.packages("ggforce")
# install.packages('ggimage')
# install.packages('Hmisc')
# install.packages("plyr")
#source('../../scib-reproducibility/visualization/plotSingleTaskRNA.R')


library(tibble)
library(RColorBrewer)
library(dynutils)
library(stringr)
library(Hmisc)
library(plyr)


# source("knit_table.R") # Please put knit_table.R in your working dir
# 
# source("R_fun_report.R")


```

```{r}
library(STACAS)
library(Seurat)
library(scIntegrationMetrics)
library(anndata)
```

## Compute true mislabelling rates
```{r}
misRateTable <- data.frame()
celltypeLabel = c("celltype","celltype","final_annotation","cell_type")
names(celltypeLabel) <- c('tcells_atlas','human_pancreas','immune_cell_hum',"lung_atlas")

atlases <- c('tcells_atlas','human_pancreas','immune_cell_hum',"lung_atlas")

for (task in atlases) {
  adata <- read_h5ad(paste0("../data/",task,"/prepare/unscaled/hvg/adata_pre.h5ad"))
  for (p in c(10,20,50,100)) {
    misRate <- table(adata$obs[,paste0('percentShuffling_',p,'_',celltypeLabel[task])] == adata$obs[,celltypeLabel[task]])[1]/length(adata$obs[,celltypeLabel[task]])
    misRateTable <- rbind(misRateTable,c(task, p, misRate))
  }
}
colnames(misRateTable) <- c("task","percentShuffling","percentMislabelling")
misRateTable$percentMislabelling <- as.numeric(misRateTable$percentMislabelling)

misRateTable$percentShuffling <- as.numeric(misRateTable$percentShuffling)
ggplot(misRateTable, aes(x = percentShuffling , y = percentMislabelling, fill = task)) + geom_bar(stat="identity", color="black", position=position_dodge())
```




```{r}
metricsR <- read.csv("../data/metrics_R.csv",row.names = 1)

scenarios <- str_split_fixed(rownames(metricsR),pattern = "/",n=7)
#head(scenarios)

scenarios <- scenarios[,-1]
colnames(scenarios) <- c("task","altered_annotations","folder","scaling","features","method")
metricsR <- cbind(scenarios,metricsR)

metricsR$method <- str_split_fixed(metricsR$method,pattern = "/",n=2)[,2]
metricsR$output <- str_split_fixed(metricsR$method,pattern = "_",n=2)[,2]
metricsR$tool <- str_split_fixed(metricsR$method,pattern = "_",n=2)[,1]

metricsR_unaltered <- read.csv("../../data/metrics_R.csv",row.names = 1)

scenarios_unaltered <- str_split_fixed(rownames(metricsR_unaltered),pattern = "/",n=6)
#head(scenarios_unaltered)

scenarios_unaltered <- data.frame(scenarios_unaltered[,-1])

colnames(scenarios_unaltered) <- c("task","folder","scaling","features","method")
scenarios_unaltered$method <- str_split_fixed(scenarios_unaltered$method,pattern = "/",n=2)[,2]



keptIndex <- which(scenarios_unaltered$task %in% atlases &
                     scenarios_unaltered$scaling %in% c("unscaled") &
                     scenarios_unaltered$method %in% c("scanvi_embed","scvi_embed","semiSupSTACAS_embed","STACAS_embed","scgen_full","unintegrated_full"))

rn <- rownames(metricsR_unaltered)[keptIndex]

metricsR_unaltered <- cbind(scenarios_unaltered[keptIndex,],metricsR_unaltered[keptIndex,])
rownames(metricsR_unaltered) <- rn

metricsR_unaltered$output <- str_split_fixed(metricsR_unaltered$method,pattern = "_",n=2)[,2]
metricsR_unaltered$tool <- str_split_fixed(metricsR_unaltered$method,pattern = "_",n=2)[,1]

metricsR_unaltered$altered_annotations = "None"

#head(metricsR_unaltered)

metricsR <- rbind(metricsR,metricsR_unaltered[,colnames(metricsR)])
#metricsR
```




```{r}
metrics <- read.csv("../data/metrics.csv",row.names = 1)

scenarios <- str_split_fixed(rownames(metrics),pattern = "/",n=7)
#head(scenarios)

scenarios <- scenarios[,-1]
colnames(scenarios) <- c("task","altered_annotations","folder","scaling","features","method")
metrics <- cbind(scenarios,metrics)

#metrics$method <- str_split_fixed(metrics$method,pattern = "/",n=2)[,2]
metrics$output <- str_split_fixed(metrics$method,pattern = "_",n=2)[,2]
metrics$tool <- str_split_fixed(metrics$method,pattern = "_",n=2)[,1]

metrics_unaltered <- read.csv("../../data/metrics.csv",row.names = 1)

scenarios_unaltered <- str_split_fixed(rownames(metrics_unaltered),pattern = "/",n=6)
#head(scenarios_unaltered)

scenarios_unaltered <- data.frame(scenarios_unaltered[,-1])

colnames(scenarios_unaltered) <- c("task","folder","scaling","features","method")
#scenarios_unaltered$method <- str_split_fixed(scenarios_unaltered$method,pattern = "/",n=2)[,2]



keptIndex <- which(scenarios_unaltered$task %in% atlases &
                     scenarios_unaltered$scaling %in% c("unscaled") &
                     scenarios_unaltered$method %in% c("scanvi_embed","scvi_embed","semiSupSTACAS_embed","STACAS_embed","scgen_full","unintegrated_full"))

rn <- rownames(metrics_unaltered)[keptIndex]


metrics_unaltered <- cbind(scenarios_unaltered[keptIndex,],metrics_unaltered[keptIndex,])

rownames(metrics_unaltered) <- rn

metrics_unaltered$output <- str_split_fixed(metrics_unaltered$method,pattern = "_",n=2)[,2]
metrics_unaltered$tool <- str_split_fixed(metrics_unaltered$method,pattern = "_",n=2)[,1]

metrics_unaltered$altered_annotations = "None"

#head(metrics_unaltered)

metrics <- rbind(metrics,metrics_unaltered[,colnames(metrics)])
#metrics




```

```{r}
metrics$altered_annotations <- factor(metrics$altered_annotations,levels = c("None", "broad",
                                                                             "percentShuffling_10","percentShuffling_20","percentShuffling_50","percentShuffling_100",
                                                                             "unknown_10", "unknown_20","unknown_50","unknown_100"))
metrics$ASW_label_raw <- 2*metrics$ASW_label-1
ggplot(metrics[grepl(metrics$altered_annotations,pattern = "percentShuffling|None"),],aes(x = altered_annotations,color=method,y=ASW_label_raw,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```
```{r}
metricsR$altered_annotations <- factor(metricsR$altered_annotations,levels = c("None", "broad",
                                                                             "percentShuffling_10","percentShuffling_20","percentShuffling_50","percentShuffling_100",
                                                                             "unknown_10", "unknown_20","unknown_50","unknown_100"))

ggplot(metricsR[grepl(metricsR$altered_annotations,pattern = "percentShuffling|None"),],aes(x = altered_annotations,color=method,y=CiLISI,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```

```{r}
ggplot(metrics[grepl(metrics$altered_annotations,pattern = "unknown|None"),],aes(x = altered_annotations,color=method,y=ASW_label_raw,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```
```{r}
ggplot(metricsR[grepl(metricsR$altered_annotations,pattern = "unknown|None"),],aes(x = altered_annotations,color=method,y=CiLISI,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```
```{r}

ggplot(metrics[grepl(metrics$altered_annotations,pattern = "broad|None"),],aes(x = altered_annotations,color=method,y=ASW_label_raw,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```


```{r}
# metricsR$altered_annotations <- factor(metricsR$altered_annotations,levels = sort(unique(metricsR$altered_annotations)))


ggplot(metricsR[grepl(metricsR$altered_annotations,pattern = "broad|None"),],aes(x = altered_annotations,color=method,y=CiLISI,group = method)) +geom_point()+ geom_line() +  facet_wrap('~task') +
  scale_x_discrete(guide = guide_axis(angle = 45))
```




```{r}
rownames(metricsR) <- gsub(rownames(metricsR),pattern = "/R/",replacement = "/")
allMetrics <- cbind(metrics,metricsR[rownames(metrics),c("CiLISI","CiLISI_means")])
```



```{r fig.height=3,fig.width=6}

for (t in unique(allMetrics$task)) {
  metricsTask <- allMetrics[allMetrics$task == t,]
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "broad|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 4)+theme(legend.position = "bottom"))
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "unknown|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 4)+theme(legend.position = "bottom"))
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "percentShuffling|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 4)+theme(legend.position = "bottom"))
}
```
```{r fig.height=0.7,fig.width=2}

for (t in unique(allMetrics$task)) {
  metricsTask <- allMetrics[allMetrics$task == t,]
  # plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "broad|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "unknown|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "percentShuffling|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
}
```

```{r}
for (t in unique(allMetrics$task)) {
  metricsTask <- allMetrics[allMetrics$task == t,]
  plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "broad|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
  # plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "unknown|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
  # plot(ggplot(metricsTask[grepl(metricsTask$altered_annotations,pattern = "percentShuffling|None"),],aes(x = CiLISI, y= ASW_label_raw, color = method, group = method)) +geom_point() + facet_wrap(c("task","altered_annotations"), ncol = 5)+theme(legend.position = "bottom"))
}
```


## Broad vs fine annotation for the T cells atlas
```{r}
tcells <- readRDS("../data/tcells_atlas/prepare/unscaled/hvg/adata_pre.RDS")
table(tcells$celltype,tcells$broad_celltype)
```




