```{r}
library(anndata)
library(Seurat)
```
```{r}
adata <- read_h5ad("../input/immune_cell_hum.h5ad")

adata
```

```{r}
seurat.obj <- CreateSeuratObject(meta.data = adata$obs,counts = t(adata$layers['counts']))
seurat.obj <- AggregateExpression(seurat.obj,group.by = "final_annotation",slot = "counts",return.seurat = T)
seurat.obj <- NormalizeData(seurat.obj)

distances <- dist(as.matrix(Matrix::t(seurat.obj@assays$RNA@data)))

library(reshape2)

distances.df <- melt(as.matrix(distances), varnames = c("row", "col"))
distances.df <- distances.df[distances.df$value != 0,]
distances.df <- distances.df[order(distances.df$value),]
distances.df <- distances.df[!duplicated(distances.df$value),]

distances.df <- distances.df[1:20,]
distances.df
for (c in c(1:20)) {
  adata$obs[,paste0("closest_",c,"_final_annotation")] <- factor(adata$obs[,"final_annotation"],
                                                                 levels = c(levels(adata$obs[,"final_annotation"]),
                                                                            "merged_type"))
  
  adata$obs[,paste0("closest_",c,"_final_annotation")][adata$obs[,paste0("closest_",c,"_final_annotation")] == as.character(distances.df[c,"row"])] <- "merged_type"
  adata$obs[,paste0("closest_",c,"_final_annotation")][adata$obs[,paste0("closest_",c,"_final_annotation")] == as.character(distances.df[c,"col"])] <- "merged_type"
  adata$obs[,paste0("closest_",c,"_final_annotation")] <- droplevels(adata$obs[,paste0("closest_",c,"_final_annotation")] )
}








```

## hiding 15% and shuffling 20% in neighbor subtypes
```{r}
getClosestSubtype <- function(distances) {
  res <- as.character(rownames(as.matrix(distances))[order(as.matrix(distances)[,1])[2]])
  return(res)
}

closestSubtypes <- apply(data.frame(as.matrix(distances)),MARGIN = 2,FUN = getClosestSubtype)
names(closestSubtypes) <- rownames(as.matrix(distances))

closestSubtypes

set.seed(2023)

#Hiding 
cells.to.hide <- sample(x = rownames(adata),
                        size = round(0.15*length(rownames(adata))))

adata$obs$neighbor_shuffled_20_unknown_15_final_annotation <- factor(adata$obs[,"final_annotation"],
                                                                              levels = c(levels(adata$obs[,"final_annotation"]),
                                                                                         "unknown"))

adata$obs[cells.to.hide,"neighbor_shuffled_20_unknown_15_final_annotation"] <- "unknown"
#shuffling neighbors
cells.to.shuffle <- sample(x = rownames(adata)[!rownames(adata) %in% cells.to.hide],
                        size = round(0.20*length(rownames(adata))))

adata$obs[cells.to.shuffle,"neighbor_shuffled_20_unknown_15_final_annotation"] <- plyr::mapvalues(x = adata$obs[cells.to.shuffle,"neighbor_shuffled_20_unknown_15_final_annotation"],
                                                                                             from = names(closestSubtypes),
                                                                                             to = closestSubtypes)

head(adata$obs[cells.to.shuffle,c("final_annotation","neighbor_shuffled_20_unknown_15_final_annotation")],n=10)
head(adata$obs[cells.to.hide,c("final_annotation","neighbor_shuffled_20_unknown_15_final_annotation")],n=10)

```


```{r fig.height=3,fig.width=3}
hclust.res <- hclust(distances)

library(ggdendro)
library(ggplot2)
dendro.plot <- ggdendrogram(hclust.res, rotate = TRUE, theme_dendro = T) 
dendro.plot <- dendro.plot + theme(axis.text.x = element_blank())
dendro.plot
saveRDS(dendro.plot,"hclust_immune.rds")


adata$obs[,"merging_0_final_annotation"] <- as.vector(adata$obs["final_annotation"]) 
merging.step <- 1
for (r in c(1:17)) {
  
  if (r <= dim(hclust.res$merge)[1]) {
    merging <- hclust.res$merge[r,]
    subtype1.num <- hclust.res$merge[r,1]
    subtype2.num <- hclust.res$merge[r,2]
    if (subtype1.num < 0) {
      subtype1 <- as.character(hclust.res$labels[-subtype1.num])
    } else {
      subtype1 <- paste0("merging_",subtype1.num)
    }
    if (subtype2.num < 0) {
      subtype2 <- as.character(hclust.res$labels[-subtype2.num])
    } else {
      subtype2 <- paste0("merging_",subtype2.num)
    }
    
    adata$obs[,paste0("merging_",merging.step,"_final_annotation")] <- factor(adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")],
                                                                              levels = c(levels(adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")]),
                                                                                         paste0("merging_",merging.step)))
    adata$obs[,paste0("merging_",merging.step,"_final_annotation")][adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")] == subtype1] <- paste0("merging_",merging.step)
    adata$obs[,paste0("merging_",merging.step,"_final_annotation")][adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")] == subtype2] <- paste0("merging_",merging.step)
    adata$obs[,paste0("merging_",merging.step,"_final_annotation")] <- droplevels(adata$obs[,paste0("merging_",merging.step,"_final_annotation")])
  } else { # duplicate final merging to have the same number (16) for each task in the workflow
    adata$obs[,paste0("merging_",r,"_final_annotation")] <- adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")]
    
  }
  merging.step <- merging.step + 1
  
}

# duplicate final merging to have the same number (15) for each dataset in the workflow

# for (r in c(merging.step:15)){
#   adata$obs[,paste0("merging_",r,"_final_annotation")] <- adata$obs[,paste0("merging_",merging.step-1,"_final_annotation")]
# }

# table(adata$obs["final_annotation"])
# table(adata$obs["merging_1_final_annotation"])
# table(adata$obs["merging_13_final_annotation"])
```


```{r}
# for (X in c(1:length(closestSubtypes))) {
#   
#   subtype1.name <- gsub(names(closestSubtypes[X]),pattern = " ",replacement = "_")
#   subtype1.name <- gsub(subtype1.name,pattern = "\\+",replacement = "pos")
#   subtype1.name <- gsub(subtype1.name,pattern = "\\-",replacement = "_")
#   subtype2.name <- gsub(as.character(closestSubtypes[X]),pattern = " ",replacement = "_")
#   subtype2.name <- gsub(subtype2.name,pattern = "\\+",replacement = "pos")
#   subtype2.name <- gsub(subtype2.name,pattern = "\\-",replacement = "_")
#   
#   if (subtype1.name > subtype2.name) {
#     anno.name <- paste0(subtype1.name,"_with_",subtype2.name,"_final_annotation")
#   } else { 
#     anno.name <- paste0(subtype2.name,"_with_",subtype1.name,"_final_annotation")
#   } 
#   
#   print(anno.name)
#   
#   if (! anno.name %in% colnames(adata$obs)) {
#     adata$obs[anno.name] <- adata$obs["final_annotation"]
#     adata$obs[anno.name][adata$obs[anno.name] == names(closestSubtypes[X])] <- closestSubtypes[X]
#     adata$obs[anno.name] <- droplevels(adata$obs[anno.name])
#   }
# }



```

```{r}


```
```{r}
cat(colnames(adata$obs)[endsWith(colnames(adata$obs),"final_annotation")],sep = "\n  - ")
```
```{r}
write_h5ad(adata,"../input/immune_cell_hum_subtype_wrongly_assigned.h5ad")
```

