  description: |
    Note\: yaml format prohibits using tabulations.

    Cluster config for scib pipeline

  author: "Leonard Herault"

  __default__:
    cpus-per-task : "16"
    N : "1"
    time : "6:00:00"
    name : "{rule}"
    partition : "partition_name"
    account : "your_account"
    mem : "64000"
    output : "cluster/snakemake/{rule}.output"
    error : "cluster/snakemake/{rule}.error"
   
  integration_run_r:
    cpus-per-task : "16"
    N : "1"
    time : "6:00:00"
    name : "{rule}"
    partition : "partition_name"
    account : "your_account"
    mem : "256000"
    output : "cluster/snakemake/{rule}.output"
    error : "cluster/snakemake/{rule}.error"
    
  metrics_single_R:
    cpus-per-task : "16"
    N : "1"
    time : "6:00:00"
    name : "{rule}"
    partition : "partition_name"
    account : "your_account"
    mem : "64000"
    output : "cluster/snakemake/{rule}.output"
    error : "cluster/snakemake/{rule}.error"
    
    
    

