ROOT: sensitivity_analysis_shuffling_neighbors
r_env : scib-R4.1
py_env : scib-pipeline-R4.1
dims: 30
unintegrated_metrics: false

INPUT_ANNOTATIONS:
  - original
  - shuffledWithGuide_5
  - shuffledWithGuide_10
  - shuffledWithGuide_15
  - shuffledWithGuide_20
  - shuffledWithGuide_25
  - shuffledWithGuide_30
  - shuffledWithGuide_35
  - shuffledWithGuide_40
  - shuffledWithGuide_45
  - shuffledWithGuide_50
  - shuffledWithGuide_60
  - shuffledWithGuide_70
  - shuffledWithGuide_80
  - shuffledWithGuide_90
  - shuffledWithGuide_100


FEATURE_SELECTION:
  hvg: 2000
  #full_feature: 0

SCALING:
  - unscaled
  - scaled

METHODS:
  scanvi:
    output_type: embed
    no_scale: true
    use_celltype: true
  scgen:
    output_type: full
    use_celltype: true
  semiSupSTACAS:
    R: true
    use_celltype: true
    output_type:
      - embed



DATA_SCENARIOS:

  immune_cell_hum:
    batch_key: batch
    label_key: final_annotation
    organism: human
    assay: expression
    file: "input/immune_cell_hum.h5ad"
    shuffling_guide: "configs/closest_subtypes_immune.csv"
    url: "https://drive.switch.ch/index.php/s/6mnRIheN1rmvYRo/download"

    
  human_pancreas:
    batch_key: tech
    label_key: celltype
    organism: human
    assay: expression
    file: "input/human_pancreas.h5ad"
    shuffling_guide: "configs/closest_subtypes_pancreas.csv"
    url: https://figshare.com/ndownloader/files/24539828
    
  tcells_atlas:
    batch_key: Study
    label_key: celltype
    organism: mouse
    assay: expression
    file: "input/tcells_atlas.h5ad"
    shuffling_guide: "configs/closest_subtypes_tcells.csv"
    url: "https://drive.switch.ch/index.php/s/QzmSXI38KiVf1Yv/download"


  lung_atlas:
    batch_key: batch
    label_key: cell_type
    organism: human
    assay: expression
    file: "input/lung_atlas.h5ad"
    shuffling_guide: "configs/closest_subtypes_lung.csv"
    url: https://figshare.com/ndownloader/files/24539942

     
